### ISSUE TITLE
Как обновить токен?

### ISSUE THREAD

**Issue by maxprig** [apiok/ok-ios-sdk#13]
Как автоматически обновить токен?

**Comment by dgreenru** [comment]
он LONG ACCESS его не нужно обновлять

**Comment by maxprig** [comment]
А пермишн LONG_ACCESS_TOKEN при авторизации не нужно указывать тогда?

**Comment by dgreenru** [comment]
нужно, если приложению выдали возможност запрашивать этот пермишен, токен будет действовать долго. Живёт токен месяцы от последнего использования.

**Comment by dgreenru** [comment]
Я предлагаю постить вопросы в чате(телеграмм или гиттер) или на стэкоферфлоу, а не создавать issue
