### ISSUE TITLE
При попытке авторизоваться выдает ошибку

### ISSUE THREAD

**Issue by maxprig** [apiok/ok-ios-sdk#14]
-canOpenURL: failed for URL: "okauth://authorize?client_id=1238296320&scope=VALUABLE_ACCESS;LONG_ACCESS_TOKEN;GROUP_CONTENT;PUBLISH_TO_STREAM;GROUP_CONTENT;LONG_ACCESS_TOKEN&redirect_uri=ok1238296320://authorize&response_type=token&layout=a&" - error: "This app is not allowed to query for scheme okauth"

В info.plist все прописано

**Comment by dgreenru** [comment]
okauth есть LSApplicationQueriesSchemes?

**Comment by dgreenru** [comment]
Я предлагаю постить вопросы в чате(телеграмм или гиттер) или на стэкоферфлоу, а не создавать issue

**Comment by maxprig** [comment]
Есть. Спасибо, я уже разобрался в проблеме.

**Comment by Woit** [comment]
@maxprig Разобрался - молодец. Но в сообществе обычно принято дописывать к радостному сообщению о победе еще и алгоритм достижения этой победы
