### ISSUE TITLE
Shared posts are not seen on my wall

### ISSUE THREAD

**Issue by tnadus** [apiok/ok-ios-sdk#2]
I entered my credentials to the sample app (appid, key, secret), and got success message when I posted something. How ever, there is nothing shown on my wall. 

What am I missing ?

**Comment by love4soul** [comment]
Are you testing in test environment? As I know your posts will not be visible until your app get approved.

**Comment by tnadus** [comment]
I've not seen any setting about test environment or any button for submission of my app for approval ?

Could you please guide me how to do this ?

Thanks

**Comment by love4soul** [comment]
I'm not sure, but probably you should fill this form http://apiok.ru/wiki/pages/viewpage.action?pageId=48463883 . I did it once for my app :)

**Comment by tnadus** [comment]
OK, I've filled the form, thanks for your help.

**Comment by tnadus** [comment]
Hello love4soul again,

My app is approved and finally I can see the posts that I share on my iOS app, thanks for your help.

I've another question, I am trying to share text with link and an icon/image, I see that there is an attachment dictionary and I've tried to add new types according to my finding on the net. 

I set it like below,

  NSDictionary *attachments = @{
        @"media" : @[@{@"text" : self.textView.text, @"type" : @"text"},
                     @{@"type" : @"link" ,@"url" : @"http://tcell.tj"}
                     /*@{@"src"  : @"img/logo.png", @"type" : @"image"}*/
                     ]
    };

text is already working and also included in the sample, I've added the link and image part. The link is working too but the image is not shown in the post. I think, I misused the image type

I just want to show an icon with the post, how should I attach this ?

**Comment by love4soul** [comment]
There is no such type as "image". You need to upload image first and then set imageId and photo token.
"type": "photo",
      "list": [
        { "id": "photoToken1" },
        { "id": "photoToken2" },
        { "photoId": "1234" }
      ]
http://apiok.ru/wiki/display/api/mediatopic.post+ru

**Comment by tnadus** [comment]
I see, thanks for your great help.
