### ISSUE TITLE
Apple rejects builds that authorize with Safari

### ISSUE THREAD

**Issue by ren6** [apiok/ok-ios-sdk#3]
10.6 Details
- Upon launching the app and tapping on some social networks buttons, a web page in mobile Safari opens for logging in, then returns the user to the app. The user should be able to log in without opening Safari first.

Please make UIWebView authorization

**Comment by idan676** [comment]
Current version execute authorization in UIWebView by default

**Comment by ren6** [comment]
Sorry, I just compared authorizeWithPermissions:inApp: method and it has YES in this SDK.
But mine somehow was set to [self authorizeWithPermissions:permissions inApp:NO];
No issue)
