### ISSUE TITLE
Ошибка Error Domain=ru.ok.sdk Code=2 "ok1234567890://authorize schema should be registered for current app"

### ISSUE THREAD

**Issue by AlexGerm** [apiok/ok-ios-sdk#9]
Вызов метода    
```javascript
[OKSDK authorizeWithPermissions:@[@"VALUABLE_ACCESS"] success:^(id response){
        NSLog(@"response: %@", response);
    }error:^(NSError *error){
        NSLog(@"error: %@", error);
    }];
```
приводит к ошибке Error Domain=ru.ok.sdk Code=2 "ok1234567890://authorize schema should be registered for current app. 
В настройках приложения на сайте занесено в список разрешенных redirect_uri занесены http://api.ok.ru/blank.html
ok1234567890://authorize
В настройках ios приложения также занесены параметры identifier: okurl, URL schemes: ok1234567890. 
В info.plist в LSApplicationQueriesSchemes занесено okauth.
Что я делаю не так?

**Comment by dgreenru** [comment]
Пофикшено в текущей версии README.md обновлён

**Comment by kolyosick** [comment]
Получаю "ok1248332800://authorize schema should be registered for current app" хотя прописал в настройках приложения. Что я делаю не так? [https://puu.sh/rrCpM/9ed630f94c.png](url)

**Comment by dgreenru** [comment]
В настройках самого IOS приложения эту схему слушаете в LSApplicationQueriesSchemes занесено?

**Comment by kolyosick** [comment]
@dgreenru уже разобрался. Нужно было в CFBundleURLSchemes прописать

**Comment by kosbar** [comment]
Ни с того  ни с сего стали получать эту ошибку
appId 200522240
